# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [2]:
baby_names = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv')
baby_names

         Unnamed: 0       Id     Name  Year Gender State  Count
0             11349    11350     Emma  2004      F    AK     62
1             11350    11351  Madison  2004      F    AK     48
2             11351    11352   Hannah  2004      F    AK     46
3             11352    11353    Grace  2004      F    AK     44
4             11353    11354    Emily  2004      F    AK     41
...             ...      ...      ...   ...    ...   ...    ...
1016390     5647421  5647422     Seth  2014      M    WY      5
1016391     5647422  5647423  Spencer  2014      M    WY      5
1016392     5647423  5647424     Tyce  2014      M    WY      5
1016393     5647424  5647425   Victor  2014      M    WY      5
1016394     5647425  5647426   Waylon  2014      M    WY      5

[1016395 rows x 7 columns]

### Step 4. See the first 10 entries

In [3]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [4]:
baby_names.drop(['Unnamed: 0', 'Id'], axis=1, inplace=True)
baby_names

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. What year has the highest number of baby names in the dataset?

In [9]:
baby_names.groupby('Year')["Count"].sum().sort_values(ascending=False)

Year
2007    3412417
2006    3387737
2008    3340318
2005    3305315
2004    3293984
2009    3232116
2010    3116548
2014    3113611
2011    3079145
2012    3073858
2013    3066443
Name: Count, dtype: int64

### Step 7. Is there more male or female names in the dataset?

In [10]:
baby_names.groupby('Gender')["Count"].sum()

Gender
F    16380293
M    19041199
Name: Count, dtype: int64

### Step 8. Group the dataset by name and assign to names

In [11]:
names = baby_names.groupby('Name')["Count"].sum()
names

Name
Aaban        12
Aadan        23
Aadarsh       5
Aaden      3426
Aadhav        6
           ...
Zyra         42
Zyrah        11
Zyren         6
Zyria        59
Zyriah       58
Name: Count, Length: 17632, dtype: int64

### Step 9. How many different names exist in the dataset?

In [12]:
names.shape[0]

17632

### Step 10. What is the name with most occurrences?

In [13]:
names.sort_values(ascending=False)

Name
Jacob       242874
Emma        214852
Michael     214405
Ethan       209277
Isabella    204798
             ...
Abigaile         5
Shatha           5
Zykeriah         5
Zunaira          5
Ezel             5
Name: Count, Length: 17632, dtype: int64

### Step 11. How many different names have the least occurrences?

In [14]:
names.sort_values(ascending=True)

Name
Shabd            5
Gatlyn           5
Gaspard          5
Garvin           5
Brizia           5
             ...
Isabella    204798
Ethan       209277
Michael     214405
Emma        214852
Jacob       242874
Name: Count, Length: 17632, dtype: int64

### Step 12. What is the median name occurrence?

In [15]:
names.median()

49.0

### Step 13. What is the standard deviation of names?

In [16]:
names.std()

11006.069467891111

### Step 14. Get a summary with the mean, min, max, std and quartiles.

In [17]:
names.describe()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64